version: '3'

services:
  db:
    image: postgres:12.7
    container_name: db
    volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER: moodle
      - POSTGRES_PASSWORD: "moodle"
      - POSTGRES_DB: moodle
    ports:
      - 5432:5432
  app:
    build: .
    command: python3 -m  flask run --host=0.0.0.0
    volumes:
    - .:/app
    ports:
    - 5000:5000
    depends_on:
      - db
