version: '3'

services:
  db:
    image: postgres:12.7
    container_name: postgres
    volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - APP_DB_USER=docker
      - APP_DB_PASS=docker
      - APP_DB_NAME=docker
    ports:
      - 5432:5432
  app:
    build: .
    command: python3 -m  flask run --host=0.0.0.0
    volumes:
    - .:/app
    ports:
    - "80:5000"
    depends_on:
      - db
